---
  - name: Install filebeat to client_node (RPM)
    dnf:
      name: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.0-x86_64.rpm"
      state: present
    when: ansible_os_family =="RedHat"

  - name: Install filebeat to client_node (DEB)
    apt:
      deb: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.0-amd64.deb"
      state: present
    when: ansible_os_family =="Debian"

  - name: Setup module to get logs from nginx
    template:
      src: filebeat.yml.j2
      dest: /etc/filebeat/filebeat.yml
    notify: Restart filebeat
