---
  - name: Install ElasticSearch
    apt:
      deb: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.0-amd64.deb"

  - name: TUNNING JVM
    copy: src=jvm.options dest=/etc/elasticsearch/jvm.options force=yes

  - name: Config Elastic MASTER
    when: ansible_hostname == "elk-node1"
    template: src=elasticsearch_master.j2 dest={{ el_conf_file }}
    notify: Elasticsearch restart

  - name: Config Elastic SLAAAAVES
    when: ansible_hostname != "elk-node1"
    template: src="elasticsearch_slave.j2" dest={{ el_conf_file }}
    notify: Elasticsearch restart

  - name: Start ElasticSearch service and make it enabled
    systemd:
      name: elasticsearch
      state: started
      enabled: yes
